### PR TITLE
Deal broken strings individualy

### PR DESCRIPTION
**Pull request by callstackexceed**
related to #22

### CODE REVIEW

**Comment by callstackexceed** [comment]
@dzx-dzx

**Review by dzx-dzx — CHANGES_REQUESTED** [review]
考虑到包围叫“enclose”，不包围真的叫“unclosed”吗……

**Comment by dzx-dzx** [comment]
另外附上足以证明正则正确性的测试截图。

**Comment by callstackexceed** [comment]
> 
> 
> 考虑到包围叫“enclose”，不包围真的叫“unclosed”吗……

unclosed means "未闭合的" here.

**Comment by callstackexceed** [comment]
> 
> 
> 另外附上足以证明正则正确性的测试截图。

I don't know wheather this is enough:
```JS
let {lex} = require("./nos.js");
console.log(lex(`1"' | 1" |   11 1| 1|'"00|1'|||1`));
/*
output:
[
  {
    typeName: 'directLiteral',
    offset: 0,
    length: 1,
    raw: '1',
    value: '1'
  },
  {
    typeName: 'stringLiteral',
    offset: 1,
    length: 7,
    raw: `"' | 1"`,
    value: "' | 1"
  },
  { typeName: 'operator', offset: 9, length: 1, raw: '|', value: '|' },
  {
    typeName: 'directLiteral',
    offset: 13,
    length: 2,
    raw: '11',
    value: '11'
  },
  {
    typeName: 'directLiteral',
    offset: 16,
    length: 1,
    raw: '1',
    value: '1'
  },
  { typeName: 'operator', offset: 17, length: 1, raw: '|', value: '|' },
  {
    typeName: 'directLiteral',
    offset: 19,
    length: 1,
    raw: '1',
    value: '1'
  },
  { typeName: 'operator', offset: 20, length: 1, raw: '|', value: '|' },
  {
    typeName: 'stringLiteral',
    offset: 21,
    length: 7,
    raw: `'"00|1'`,
    value: '"00|1'
  },
  { typeName: 'operator', offset: 28, length: 1, raw: '|', value: '|' },
  { typeName: 'operator', offset: 29, length: 1, raw: '|', value: '|' },
  { typeName: 'operator', offset: 30, length: 1, raw: '|', value: '|' },
  {
    typeName: 'directLiteral',
    offset: 31,
    length: 1,
    raw: '1',
    value: '1'
  }
]
 */
```

**Comment by dzx-dzx** [comment]
> ```js
> 1"' | 1" |   11 1| 1|'"00|1'|||1
> ```

所以我看到它没有识别出任何一段是不闭合的，这是符合预期的？

**Comment by callstackexceed** [comment]
> > > 考虑到包围叫“enclose”，不包围真的叫“unclosed”吗…… 
> >
> > unclosed means "未闭合的" here. 
> 
> 我知道，但我不认为这是正确的翻译。 
>

I think you can use unmatch like unmatched quote quotation,
but for a string, it's an unclosed string.

**Comment by dzx-dzx** [comment]
image
这是正常的？

**Comment by callstackexceed** [comment]
> image
>
> 这是正常的？

Yes.

**Pull request merged**
